# This file is a template, and might need editing before it works on your project.
# https://medium.com/version-1/flutter-continuous-integration-using-gitlab-80f3d896704a
# https://hub.docker.com/r/google/dart
image: cirrusci/flutter:stable

variables:

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .pub-cache/global_packages

stages:
  - analyze_and_test
   - release

before_script:
  - export PATH="$PATH":"$HOME/.flutter-sdk/.pub-cache/bin"
  - flutter pub get
  - flutter clean
  - flutter --version
  - flutter pub global activate dart_dot_reporter

analyze_and_test:
  stage: analyze_and_test
  script:
    - flutter analyze
    - flutter test --machine > machine.log
    - flutter pub global run dart_dot_reporter machine.log


release:staging:
  stage: release
  when: manual
  script:
    - curl -H "Content-Type:application/json" -H "x-auth-token:WIT5U4VFjsg_z6xQNgsAn04brfDpgaqnvSnytd1uP80" https://api.codemagic.io/builds --data '{"appId":"https://codemagic.io/app/6238b868854b7237ec0bc63f/workflow/6238b868854b7237ec0bc63e/settings", "workflowId":"6238b868854b7237ec0bc63e","branch":"staging"}'
  only:
    refs:
      - staging